development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: dp_development
  username: postgres
  password: root
  pool: 5

test:
  adapter: postgresql
  host: localhost
  port: 5432
  database: dp_test
  username: postgres
  password: root
  pool: 5

production:
  adapter: postgresql
  host: localhost
  port: 5432
  database: dp_production
  username: postgres
  password: root
  pool: 5